server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: prod
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

zone:
  session:
    cookie-name: BKS_ZONE_SESSION
    cookie-max-age: 180
    timeout-minutes: 3
